### ISSUE TITLE
使用源码构建吗，demo验证微服引擎功能，发现配置中下发不生效，是project参与导致，建议默认删除这段配置

### ISSUE THREAD

**Issue by develpoerX** [huaweicloud/spring-cloud-huawei-samples#43]
建议默认配置项目注释掉此模块   
   # Configure AK/SK credentials if needed. Default not enabled.
      credentials:
        enabled: false
        accessKey: your ak
        secretKey: your sk
        akskCustomCipher: default
        project: cn-south-1

**Comment by brt2cv** [comment]
enabled: false
可以保留，方便需要时激活

**Comment by zhaozw** [comment]
project: default 是不是好一些，之前就是因为这个project配置错误的问题调试好久才发现

**Comment by liubao68** [comment]
DEMO里面把credentials配置删除

**Comment by liubao68** [comment]
removed
