### ISSUE TITLE
spring-cloud-huawei-samples 这个版本的 有啥优势,对接啥模块?

### ISSUE THREAD

**Issue by ithjz** [huaweicloud/spring-cloud-huawei-samples#8]
spring-cloud-huawei-samples 这个版本的 有啥优势,对接啥模块?

**Comment by liubao68** [comment]
参考材料：
*  [华为云CSE](https://support.huaweicloud.com/devg-servicestage/ss-devg-0002.html)
* [Spring Cloud Huawei](https://github.com/huaweicloud/spring-cloud-huawei)
